# Pytorch Fundamentals 

In [5]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
torch.__version__

'2.1.0.dev20230326+cu117'

## Introduction to Tensors

### Creating Tensors
_A scalar is a single number, in tensor terms a zero dimensional.<br> A vector has magnitude and direction, in tensor terms one dimensional. <br> A matrix is a 2-D array of numbers, in tensor terms two dimensional. <br> A Tensor is an n-D array of numbers, can have any dimension; 0 - scalar, 1 - vector. <br> Tensors are created using [torch.Tensor()](https://pytorch.org/docs/stable/tensors.html). <br>_
_'shape' attribute tells how the elements are arranged_ 

In [16]:
scalar = torch.tensor(7)
scalar 

tensor(7)

In [17]:
scalar.ndim

0

In [18]:
# Get Tensor back as python integer
scalar.item()

7

In [19]:
scalar.shape

torch.Size([])

In [20]:
vector = torch.tensor([6,9])
vector

tensor([6, 9])

In [21]:
vector.ndim

1

In [22]:
vector.shape

torch.Size([2])

In [23]:
MATRIX = torch.tensor([[6,9],[2, 1]])
MATRIX

tensor([[6, 9],
        [2, 1]])

In [24]:
MATRIX.ndim

2

In [25]:
MATRIX.shape

torch.Size([2, 2])

In [29]:
MATRIX[0]

tensor([6, 9])

In [30]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [31]:
TENSOR.ndim

3

In [32]:
TENSOR.shape

torch.Size([1, 3, 3])

In [33]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors
_Many neural networks learn by starting with tensors full of random numbers and then adjust those random numbers to better represent the data._

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [54]:
random_tensor = torch.rand(2,4)
random_tensor

tensor([[0.1905, 0.7267, 0.3833, 0.6602],
        [0.1896, 0.8768, 0.9446, 0.9420]])

In [73]:
# Creating a random tensor with similar shape to an image tensor
image_tensor = torch.rand(size=(224,224,3))
image_tensor.ndim, image_tensor.shape

(3, torch.Size([224, 224, 3]))

In [71]:
my_tensor = torch.rand(3,3,3)
my_tensor

tensor([[[0.4536, 0.5566, 0.4520],
         [0.6117, 0.9687, 0.1806],
         [0.9007, 0.5982, 0.6518]],

        [[0.6614, 0.7926, 0.5377],
         [0.3310, 0.2600, 0.0893],
         [0.6454, 0.7539, 0.6246]],

        [[0.8798, 0.3365, 0.5174],
         [0.9060, 0.6705, 0.3923],
         [0.1854, 0.5891, 0.7569]]])

### Zeros and Ones 

In [75]:
zeros = torch.zeros(size=(2,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [76]:
ones = torch.ones(size=(2,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [77]:
ones.dtype

torch.float32

### Creating a range of tensors
_torch.arange(start= , end= , step =)_

In [80]:
one_to_ten = torch.arange(start=0, end=10, step=0.5)
one_to_ten

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000, 5.0000, 5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000,
        9.0000, 9.5000])

In [82]:
tenx2_ones = torch.ones_like(input=one_to_ten)
tenx2_ones

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.])

### Tensor datatypes
_Tensors by default are float32_

In [87]:
float_32_tensor = torch.tensor([5.0, 2, 3.64], dtype=None, device="cuda", requires_grad=False)
float_32_tensor.dtype

torch.float32

In [89]:
float16_tensor = float_32_tensor.type(torch.float16)
float16_tensor.dtype

torch.float16

### Getting Tensor Attributes

In [98]:
some_tensor = torch.rand(2,4, device="cuda")
some_tensor

tensor([[0.8302, 0.6967, 0.6028, 0.4207],
        [0.3919, 0.5503, 0.6098, 0.2524]], device='cuda:0')

In [100]:
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device of tensor:{some_tensor.device}")

Datatype of tensor:torch.float32
Shape of tensor:torch.Size([2, 4])
Device of tensor:cuda:0


### Tensor Operations
Tensor Operations include:
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [121]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [102]:
tensor * 2

tensor([2, 4, 6])

In [103]:
tensor - 2

tensor([-1,  0,  1])

In [104]:
torch.mul(tensor,10)

tensor([10, 20, 30])

### Multiplication
Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules for **matrix multiplication**:
1. Inner dimensions must match:
* `(x,y) @ (x, y)` won't work
* `(x,y) @ (y, x)` will work
2. Resulting matrix has the shape of the outer dimensions

`torch.mm()` is short for `torch.matmul()`

In [117]:
tensor * tensor

tensor([1, 4, 9], device='cuda:0')

In [113]:
torch.matmul(tensor, tensor) # matrix multiplication - multiples each element by itself and sums the total

tensor(14)

In [122]:
tensor @ tensor

tensor(14)

In [124]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 23 µs, sys: 20 µs, total: 43 µs
Wall time: 44.3 µs


tensor(14)

In [125]:
tenA = torch.tensor ([[1,2],[3,4],[5,6]])
tenB = torch.tensor ([[10,20],[30,40],[50,60]])


In [126]:
torch.matmul(tenA, tenB)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [128]:
tenB.T

tensor([[10, 30, 50],
        [20, 40, 60]])

In [130]:
torch.matmul(tenA,tenB.T)

tensor([[ 50, 110, 170],
        [110, 250, 390],
        [170, 390, 610]])

In [131]:
torch.mm(tenA, tenB.T)

tensor([[ 50, 110, 170],
        [110, 250, 390],
        [170, 390, 610]])

### Finding the min, max, mean, sum etc

In [144]:
x = torch.arange(0,100,10, dtype=torch.float32)
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [139]:
torch.min(x) #or x.min()

tensor(0.)

In [140]:
torch.max(x)

tensor(90.)

In [145]:
torch.mean(x) #requires tensor in float32 dataype

tensor(45.)

In [142]:
torch.sum(x)

tensor(450.)

In [146]:
torch.argmax(x) #index of max value

tensor(9)

In [150]:
torch.argmin(x) #index of min value

tensor(0)

In [152]:
x[9], x[0]

(tensor(90.), tensor(0.))

### Reshaping, Viewing, Stacking, Squeezing and Unsqueezing Tensors
* Reshaping - reshapes an input tensor to defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions swapped in a certain way


In [153]:
y = torch.arange(1.0, 10.)
y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [170]:
y_reshaped = y.reshape(1,9)
y_reshaped, y_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [156]:
y_reshaped = y.reshape(9,1)
y_reshaped, y_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [157]:
z = y.view(1,9)
z , z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [166]:
# Changing z changes x (view of a tensor shares the same memory as the original)
z[:,0] = 5 
z,y

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [165]:
# Stacking tensors on top of each other
y_stacked = torch.stack([y,y,y,y],dim = 0) 
y_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [163]:
y_stacked = torch.stack([y,y,y,y],dim = 1)
y_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [171]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor and shape:{y_reshaped,y_reshaped.shape}")
y_squeezed = y_reshaped.squeeze()
print(f"Squeezed tensor and shape:{y_squeezed,y_squeezed.shape}")

Previous tensor and shape:(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))
Squeezed tensor and shape:(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))


In [174]:
# torch.unsqueeze() - adds a single dimensions to a target tensor
print(f"Target tensor and shape:{y_squeezed,y_squeezed.shape}")
y_unsqueezed = y_squeezed.unsqueeze(dim=0)
print(f"New tensor and shape:{y_unsqueezed,y_unsqueezed.shape}")

Target tensor and shape:(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))
New tensor and shape:(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))


In [177]:
# torch.permute - rearranges the dimensions of a target tensor to a specified order
y_og = torch.rand(size=(200, 100, 300))
y_permuted = y_og.permute(2,0,1)

print(f"Previous Shape: {y_og.shape}")
print(f"New Shape: {y_permuted.shape}")



Previous Shape: torch.Size([200, 100, 300])
New Shape: torch.Size([300, 200, 100])


### Indexing

In [179]:
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [180]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [182]:
x[0][0]

tensor([1, 2, 3])

In [186]:
x[0][0][2]


tensor(3)

In [187]:
x[0][1][2]


tensor(6)

In [188]:
x[0][2][2]


tensor(9)

In [189]:
# `:` can be used to select `all` of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [190]:
x[:,2]


tensor([[7, 8, 9]])

In [191]:
# get all values of 0th and 1st dim but only index 1 of 2nd dim
x[:,:,1]

tensor([[2, 5, 8]])

In [193]:
# get all values of the 0 dim but only the 1st index value of 1st and 2nd dim
x[:,1, 1]

tensor([5])

In [194]:
# get index 0 of the 0th and 1st dim and all values of 2nd dim
x[0,0,:]

tensor([1, 2, 3])

In [206]:
# index on x to return 9 , 3 6 9
x[0,2,2] , x[:,:,2]

(tensor(9), tensor([[3, 6, 9]]))

### Pytorch tensors & NumPy
* Data in Numpy, to PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor to Numpy array -> `torch.Tensor.numpy()`

Default numpy datatype is float64

In [208]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [209]:
# Tensor to NumPy array
tensor = torch.ones(6)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducability 

to reduce the randomness in neural networks and pytorch -> random seed
manual seed works for only one block, so call it again to replicate

In [216]:
rndtenA = torch.rand(2,4)
rndtenB = torch.rand(2,4)

rndtenA, rndtenB, rndtenA == rndtenB

(tensor([[0.9408, 0.1332, 0.9346, 0.5936],
         [0.8694, 0.5677, 0.7411, 0.4294]]),
 tensor([[0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]),
 tensor([[False, False, False, False],
         [False, False, False, False]]))

In [215]:
torch.manual_seed(42)
rndtenC = torch.rand(2,4)

torch.manual_seed(42)
rndtenD = torch.rand(2,4)

rndtenC, rndtenD, rndtenC == rndtenD  

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936]]),
 tensor([[True, True, True, True],
         [True, True, True, True]]))

### Running on GPUs

[CUDA Best practices](https://pytorch.org/docs/stable/notes/cuda.html#best-practices)

In [217]:
! nvidia-smi


Thu Mar 30 12:46:46 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.89.02    Driver Version: 525.89.02    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   53C    P8    37W / 370W |    729MiB / 24576MiB |     28%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [218]:
torch.cuda.is_available()

True

In [219]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [220]:
torch.cuda.device_count()

1

In [221]:
tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [222]:
tensor = tensor.to(device)
tensor

tensor([1, 2, 3], device='cuda:0')

In [224]:
# moving tensors back to cpu, numpy doesn't work on GPU
tensor_back_on_cpu = tensor.cpu().numpy()
tensor_back_on_cpu


array([1, 2, 3])

### Three Most Common Errors in PyTorch
* **Shape errors** - shapes of matrices/tensor doesn't line up
* **Device errors** - model is on a different device to data
* **Datatype errors** - data is on one type but the operation requires another datatype