# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
import torch

rand_tensor = torch.rand(7,7)
rand_tensor

tensor([[0.4983, 0.8317, 0.0119, 0.4565, 0.6356, 0.4515, 0.8361],
        [0.8020, 0.1010, 0.3732, 0.2927, 0.0681, 0.2134, 0.1046],
        [0.1507, 0.1173, 0.2543, 0.6598, 0.0495, 0.2631, 0.5531],
        [0.1120, 0.1739, 0.3330, 0.1990, 0.8175, 0.7403, 0.4794],
        [0.7362, 0.1616, 0.5445, 0.7180, 0.4172, 0.9174, 0.6294],
        [0.2983, 0.0759, 0.3448, 0.8864, 0.6750, 0.1630, 0.0499],
        [0.4884, 0.7493, 0.0577, 0.4843, 0.5328, 0.2885, 0.7530]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
tenb = torch.rand(1,7)

torch.mm(rand_tensor,tenb.T)


tensor([[1.7353],
        [1.4117],
        [1.0639],
        [1.3269],
        [2.2713],
        [1.4791],
        [1.6416]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [9]:
torch.manual_seed(0)
tenA = torch.rand(7,7)

tenB = torch.rand(1,7)

tenC = torch.mm(tenA, tenB.T)
tenC, tenC.shape


(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [10]:
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [27]:
torch.manual_seed(1234)

Device = "cuda" if torch.cuda.is_available() else "cpu"

print(f"Device: {Device}")

tenA = torch.rand(2, 3).to(Device)
tenB = torch.rand(2, 3).to(Device)

tenA, tenB



Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [28]:
tenC = torch.mm(tenA, tenB.T)
tenC, tenC.shape


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [18]:
torch.max(tenC), torch.min(tenC)

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [19]:
torch.argmax(tenC), torch.argmin(tenC)


(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [25]:
torch.manual_seed(7)

tenA = torch.rand(1,1,1,10)

# torch.manual_seed(7)
# tenB = torch.rand(1,1,1,10)

# tenB = tenB.squeeze()
tenB = tenA.squeeze()
print(tenA,tenA.shape)
print(tenB,tenB.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
